### ISSUE TITLE
StorageAccount Validation Error

### ISSUE THREAD

**Issue by riweston** [jlucktay/stack#61]
Hi mate,

This is the config on my Linux machine...

```shell
$ stack version
Using config file: /home/richard/.config/stack/stack.config.json
stack v0.8.0 from commit 89bbd89, built 2019-10-08T13:13:48Z by GoReleaser.
```

```shell
$ az --version
azure-cli                         2.0.74
command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3
Python location '/opt/brew/Cellar/azure-cli/2.0.74/libexec/bin/python'
Extensions directory '/home/richard/.azure/cliextensions'
Python (Linux) 3.7.4 (default, Oct  9 2019, 15:13:37)
[GCC 9.1.0]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

```json
{
	"azureDevOps": {
		"buildDefID": 5,
		"org": "DanClzAutomation",
		"pat": "$redacted",
		"project": "DanMigrationFactory"
	},
	"github": {
		"org": "Dentsu-Aegis-Network-Global-Technology",
		"pat": "$redacted",
		"repo": "dan-migration-factory"
	},
	"stackPrefix": "/subscriptions_stacks/",
	"azure": {
		"state": {
			"keyPrefix": "dantfstate",
			"storageAccount": "azeuw1azuredevopstfstate",
			"subscription": "$redacted"
			},
		"subscriptions": {
			"apparea_nonprod": "$redacted",
			"apparea_prod": "$redacted",
			"hub": "$redacted",
			"sandbox": "$redacted"
		}
	}
}
```

This is the error I receive...

```shell
$ stack init
Using config file: /home/richard/.config/stack/stack.config.json
panic: storage.AccountsClient#ListKeys: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value="" details: value length must be greater than or equal to 1
goroutine 1 [running]:
github.com/jlucktay/stack/pkg/common.mustGetStorageAccountKey(0xaaf436, 0x8)
/drone/src/pkg/common/azure.go:22 +0x245
github.com/jlucktay/stack/pkg/common.InitStack()
/drone/src/pkg/common/init.go:33 +0x2b0
github.com/jlucktay/stack/pkg/cmd/init.NewCommand.func1(0xc00016c500, 0xfa9628, 0x0, 0x0)
/drone/src/pkg/cmd/init/init.go:18 +0x20
github.com/spf13/cobra.(*Command).execute(0xc00016c500, 0xfa9628, 0x0, 0x0, 0xc00016c500, 0xfa9628)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d1900, 0xc000133f10, 0x6, 0x6)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jlucktay/stack/cmd.Execute()
/drone/src/cmd/root.go:58 +0x2b0
main.main()
/drone/src/main.go:6 +0x20
```

Cheers, Rich

**Comment by jlucktay** [comment]
That's coming from the change in v0.8.0.
Now that it's using the Azure SDK directly, rather than piggybacking on the Azure CLI, it needs to know the name of the resource group holding the storage account: https://github.com/jlucktay/stack#stack-init-relevant-config-keys
